### PR TITLE
Added more methods to the generator and readme changes!

### PR DESCRIPTION
**Pull request by furtidev**
### In this PR:

- [x] README.md changes. Centered some text and stuff.
- [x] Added ~~`country()`~~, `ipv4()`, `job_title()`.
- [x] Wrote tests for the newly added methods.
- [x] Added support for the new methods in the CLI.
- [x] Added a new method in `random_profile/utils.py` called `ipv4_gen()`

Issue: #9

### CODE REVIEW

**Comment by codePerfectPlus** [comment]
There is an issue. You have added other countries as well but still, we have a street name, Cities name, and state name of the USA. so it will not generate a good combination. I was not added other countries data because of the same issue.

**Comment by furtidev** [comment]
@codePerfectPlus Native GitHub markdown doesn't support text alignment. Do you want to get rid of it all together? Also, yeah, I agree with your point. I've removed all `country` related items from the PR.

**Comment by codePerfectPlus** [comment]
> @codePerfectPlus Native GitHub markdown doesn't support text alignment. Do you want to get rid of it (text alignment) all together? Also, yeah, I agree with your point. I've removed all `country` related items from the PR.

I saw it now on your fork, It's looking better now. only remove the country support for now.

**Comment by furtidev** [comment]
> > @codePerfectPlus Native GitHub markdown doesn't support text alignment. Do you want to get rid of it (text alignment) all together? Also, yeah, I agree with your point. I've removed all `country` related items from the PR.
> 
> I saw it now on your fork, It's looking better now. only remove the country support for now.

Yeah, I did that. Please check.

**Comment by codePerfectPlus** [comment]
@furtidev Please add the job title and IP in `full_profile` output then I will merge it. Looks fine to me

**Comment by furtidev** [comment]
> @furtidev Please add the job title and IP in `full_profile` output then I will merge it. Looks fine to me

Oh, I missed that. Thanks for point out, keep an eye out, the commit will be coming any minute.

**Review by codePerfectPlus — APPROVED** [review]
Thanks for making your contributions.

you can join us on telegram for more updates about Hacktoberfest.

Join Hacktoberfest Community Channels/Server.

 - [Telegram](https://t.me/hacktober2022)
 - [Discord](https://discord.gg/JfbK3bS)

Happy hacktoberfest

**Pull request merged**
