### PR TITLE
added first names

### PR DESCRIPTION
**Pull request by devshaki**

### CODE REVIEW

**Comment by codePerfectPlus** [comment]
that's great, Please create an assets folder inside the same directory(in which the txt file you added) and move the txt file in it.

**Comment by devshaki** [comment]
I will do it right now

**Comment by devshaki** [comment]
@codePerfectPlus i did it + added bigger list of last names

**Comment by codePerfectPlus** [comment]
@devshaki Please also solve the review changes, adding for loop will increase the execution time

**Comment by devshaki** [comment]
@codePerfectPlus i sorry i dont understand, do you mean the loop of reading it?

**Comment by devshaki** [comment]
because if yes i can fix it rq

**Comment by codePerfectPlus** [comment]
@devshaki I fixed it

**Review by codePerfectPlus — APPROVED** [review]
Thanks for making your contributions.

you can join us on telegram for more updates about Hacktoberfest.

Join Hacktoberfest Community Channels/Server.

 - [Telegram](https://t.me/hacktober2022)
 - [Discord](https://discord.gg/JfbK3bS)

Happy hacktoberfest

**Pull request merged**
